### ISSUE TITLE
Bootstrap error

### ISSUE THREAD

**Issue by xwmario** [xfalcox/discourse-signatures#1]
RuntimeError: cd /var/www/discourse && gem update bundler failed with return #<Process::Status: pid 372 exit 1>
Location of failure: /pups/lib/pups/exec_command.rb:105:in `spawn'
exec failed with the params {"cd"=>"$home", "hook"=>"web", "cmd"=>["gem update bundler", "chown -R discourse $home"]}
e3eb42fd26ad5868fb1202ea7713fc7133637e00179d3c5656a02ebe6a514566
*\* FAILED TO BOOTSTRAP *\* please scroll up and look for earlier error messages, there may be more than one

When i remove the signature plugin app.yml, it works fine - Using the latest one

**Comment by xfalcox** [comment]
I'm looking at this tonight, thanks for the report!

**Comment by xfalcox** [comment]
Fixed on 65d24d2b982f6f60fd0794859b5e10054e4638b5

Turns out if I include the files they work! :laughing:
