### ISSUE TITLE
Enabling advanced settings break Discourse 1.9

### ISSUE THREAD

**Issue by cataldoc** [xfalcox/discourse-signatures#11]
Hello

as mentioned here: https://meta.discourse.org/t/discourse-signatures/42263/29?u=cataldo_cigliola 

Enabling advanced settings break Discourse. Also once enabled it's impossible to rebuld Discourse container as it throws an error during bundle exec rake db:migrate

Only way to recover from that is to disable this plugin

**Comment by rsmything** [comment]
https://meta.discourse.org/t/discourse-signatures/42263/33?u=rs.mything
The same issue

**Comment by xfalcox** [comment]
Fixed on https://github.com/discourse/discourse-signatures
