### ISSUE TITLE
Plugin installed but not showing in user profile

### ISSUE THREAD

**Issue by Cryzin** [xfalcox/discourse-signatures#9]
Plugin shows up in plugins list as active but does not show up under user profiles. 

Tried clearing cache and force refresh.

**Comment by xfalcox** [comment]
You need to enable it on admin settings, and enable it on your user preferences too.

**Comment by Cryzin** [comment]
It's enabled in admin but doesn't show up under user preferences

**Comment by xfalcox** [comment]
Can you share the URL where this is happening ?

**Comment by CrypticCube** [comment]
forum.moonsquads.com

**Comment by xfalcox** [comment]
I just created an account there please contact me there.

**Comment by xfalcox** [comment]
User was using a not up to date fork.
